feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        # 暴露该端点,否则无法访问
        include: hystrix.stream
spring:
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    sender:
      type: rabbit