zuul:
  routes:
    # 这里的article-service可以以随便写，但一般是微服务名
    # 代表用path替换article-service
    article-service:
      path: /article/**
spring:
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  session:
    store-type: redis
    redis:
      # 很重要，否则会导致session冲突，因此必须设置命名空间，相当于一个key
      namespace: oauth2:${spring.application.name}
  redis:
    host: localhost
    port: 6379
  zipkin:
    sender:
      type: rabbit
# 自定义属性
oauth2:
  server:
    path: http://localhost:5000/uac
security:
  oauth2:
    client:
      client-id: hx-client
      client-secret: 123
      user-authorization-uri: ${oauth2.server.path}/oauth/authorize
      access-token-uri: ${oauth2.server.path}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2.server.path}/oauth/token_key