zuul:
  routes:
    # 这里的article-service可以以随便写，但一般是微服务名
    # 代表用path替换article-service
    article-service:
      path: /article/**
spring:
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    sender:
      type: rabbit