spring:
  application:
    name: zuul
server:
  port: 8000
eureka:
  client:
    service-url:
      # 指定注册中心的地址
      defaultZone: http://localhost:1000/eureka
zuul:
  routes:
    # 这里的article-service可以以随便写，但一般是微服务名
    # 代表用path替换article-service
    article-service:
      path: /article/**


