eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:1001/eureka,http://peer2:1002/eureka
server:
  port: 1003