eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:1001/eur0eka,http://peer3:1003/eureka

server:
  port: 1200
logging:
  level:
    root: info
    top.ryan1h.springcloud.template: info
  file: ${user.dir}/log/${spring.application.name}/logger.log