spring:
  application:
    name: discovery
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 5
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 1000